CREATE TABLE WAITER_NAMES (
id SERIAL PRIMARY KEY,
NAMES text NOT NULL,
SURNAME text NOT NULL,
EMAIL text NOT NULL,
USER_CODE varchar (255)
);

CREATE TABLE WEEKDAYS (
id SERIAL PRIMARY KEY,
DAY text NOT NULL
);

CREATE TABLE TABLEREFF (
id SERIAL PRIMARY KEY,
NAMES_ID INT NOT NULL,
DAY_ID INT NOT NULL,
FOREIGN KEY (NAMES_ID) REFERENCES WAITER_NAMES(id),
FOREIGN KEY (DAY_ID) REFERENCES  WEEKDAYS(id)
);



insert into WEEKDAYS (DAY) values ('MONDAY');
insert into WEEKDAYS (DAY) values ('TUESDAY');
insert into WEEKDAYS (DAY) values ('WEDNESDAY');
insert into WEEKDAYS (DAY) values ('THURSDAY');
insert into WEEKDAYS (DAY) values ('FRIDAY');
insert into WEEKDAYS (DAY) values ('SATURDAY');
insert into WEEKDAYS (DAY) values ('SUNDAY');